version: "3.2"

services:
  lendroid:
    build:
      context: .
    volumes:
    - .:/src
  geth_rpc:
    image: ethereum/client-go
    volumes:
    - ./data:/data
    command:
    - geth
    - --identity "LocalNet"
    - --datadir /data
    - --nodiscover
    - --fast
    - --cache=512
    - --networkid 14
    - --rpc
    ports:
    - "8545:8545"
    - "30303:30303"
  ganache-cli:
    image: tiabas/ganache-cli
    volumes:
    - ./data:/data
    entrypoint:
      - ganache-cli
      - --networkId 7
      - --port 8545
      - --defaultBalanceEther 100000
      - --gasPrice 1
      - --db /data/0x_snapshot
      - --debug
    ports:
      - "8545:8545"
