version: "3.2"

services:
  lendroid:
    build:
      context: .
    volumes:
    - .:/src
  ganache-cli:
    image: tiabas/ganache-cli
    volumes:
    - ./data:/data
    entrypoint:
      - ganache-cli
      - --accounts 0
      - --networkId 7
      - --accounts 4
      - --port 8545
      - --defaultBalanceEther 100000
      - --gasPrice 1
      - --db /data/snapshot
      - --debug
    ports:
      - "8545:8545"
